kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv 
  namespace: todo3tier
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  PersistentVolumeClaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/mysql
    type: DirectoryOrCreate
